In [1]:
import pandas as pd

df=pd.read_csv('fishspice_daily Kopie.csv')

In [2]:
df

                                                          DailyFishPrices
ItemID Categorys Monday Tuesday Wednesday Thursday Friday          status
S001   Spices    5      6       4         5        3                  yes
S002   Spices    2      3       2         1        2                  yes
F001   Fish      4      5       6         5        6                  yes
F002   Fish      1      0       -2        3        4                  yes

In [3]:
import pandas as pd

# excluding the file
df_filtered= pd.read_csv("fishspice_daily Kopie.csv", header=1)

In [4]:
df_filtered

  ItemID Categorys  Monday  Tuesday  Wednesday  Thursday  Friday status
0   S001    Spices       5        6          4         5       3    yes
1   S002    Spices       2        3          2         1       2    yes
2   F001      Fish       4        5          6         5       6    yes
3   F002      Fish       1        0         -2         3       4    yes

In [10]:
df_filtered.loc[3, 'Wednesday']=2

In [11]:
df_filtered

  ItemID Categorys  Monday  Tuesday  Wednesday  Thursday  Friday status
0   S001    Spices       5        6          4         5       3    yes
1   S002    Spices       2        3          2         1       2    yes
2   F001      Fish       4        5          6         5       6    yes
3   F002      Fish       1        0          2         3       4    yes

In [12]:
# Save to CSV file
df_filtered.to_csv("filtered_fish_prices.csv", index=False)