In [1]:
import pandas as pd

df=pd.read_excel('tour_de_france.xlsx')

In [2]:
df

,Winner's avg speed,Total distance (km),Number of stages,Finishers,Entrants,Winner,Winner's Nationality,Winner's Team,Start/Finish Cities,Start/Finish City Coordinates,Start/Finish Dates
0,25.680,2428.0,6,21,60,Maurice Garin,France,La Française,Paris - Paris,"48.8566, 2.3522 - 48.8566, 2.3522",7/1/1903 - 7/21/1903
1,25.270,2420.0,6,27,88,Henri Cornet,France,Cycles JC,Paris - Paris,"48.8566, 2.3522 - 48.8566, 2.3522",7/2/1904 - 7/24/1904
2,27.110,2994.0,11,24,60,Louis Trousselier,France,Cycles Peugeot,Paris - Paris,"48.8566, 2.3522 - 48.8566, 2.3522",7/9/1905 - 7/30/1905
3,24.460,4545.0,13,14,82,René Pottier,France,Cycles Peugeot,Paris - Paris,"48.8566, 2.3522 - 48.8566, 2.3522",7/4/1906 - 7/29/1906
4,28.470,4488.0,14,33,93,Lucien Petit-Breton,France,Cycles Peugeot,Paris - Paris,"48.8566, 2.3522 - 48.8566, 2.3522",7/8/1907 - 8/4/1907
...,...,...,...,...,...,...,...,...,...,...,...
98,39.880,3496.9,20,153,198,Bradley Wiggins,United Kingdom,Team Sky,Liège - Paris,"50.6326, 5.5797 - 48.8566, 2.3522",6/30/2012 - 7/22/2012
99,40.540,3403.5,21,169,198,Chris Froome,United Kingdom,Team Sky,Porto Vecchio - Paris,"41.5914, 9.2783 - 48.8566, 2.3522",6/29/2013 - 7/21/2013
100,40.690,3659.0,21,164,198,Vincenzo Nibali,Italy,Astana,Leeds - Paris,"53.8578, -1.5023 - 48.8566, 2.3522",7/5/2014 - 7/27/2014
101,39.640,3360.3,21,160,198,Chris Froome,United Kingdom,Team Sky,Utrecht - Paris,"52.0907, 5.1214 - 48.8566, 2.3522",7/4/2015 - 7/26/2015
102,39.616,3534.0,21,174,198,Chris Froome,United Kingdom,Team Sky,Mont St. Michel - Paris,"48.6361, -1.5115 - 48.8566, 2.3522",7/2/2016 - 7/21/2016

In [3]:
df["Winner's Nationality"] = df["Winner's Nationality"].replace("Result voided", "United States")

In [4]:
df.to_excel('tour_de_france.xlsx', index=False)

In [17]:
df["Winner"]

0            Maurice Garin
1             Henri Cornet
2        Louis Trousselier
3             René Pottier
4      Lucien Petit-Breton
              ...
98         Bradley Wiggins
99            Chris Froome
100        Vincenzo Nibali
101          Chris Froome
102          Chris Froome
Name: Winner, Length: 103, dtype: object

In [10]:
df[df["Winner's Nationality"] == "Result voided"]

Empty DataFrame
Columns: [Winner's avg speed, Total distance (km), Number of stages, Finishers, Entrants, Winner, Winner's Nationality, Winner's Team, Start/Finish Cities, Start/Finish City Coordinates, Start/Finish Dates]
Index: []

In [7]:
df[df["Winner's Nationality"] == "United States"]

,Winner's avg speed,Total distance (km),Number of stages,Finishers,Entrants,Winner,Winner's Nationality,Winner's Team,Start/Finish Cities,Start/Finish City Coordinates,Start/Finish Dates
0,25.680,2428.0,6,21,60,Maurice Garin,United States,La Française,Paris - Paris,"48.8566, 2.3522 - 48.8566, 2.3522",7/1/1903 - 7/21/1903
1,25.270,2420.0,6,27,88,Henri Cornet,United States,Cycles JC,Paris - Paris,"48.8566, 2.3522 - 48.8566, 2.3522",7/2/1904 - 7/24/1904
2,27.110,2994.0,11,24,60,Louis Trousselier,United States,Cycles Peugeot,Paris - Paris,"48.8566, 2.3522 - 48.8566, 2.3522",7/9/1905 - 7/30/1905
3,24.460,4545.0,13,14,82,René Pottier,United States,Cycles Peugeot,Paris - Paris,"48.8566, 2.3522 - 48.8566, 2.3522",7/4/1906 - 7/29/1906
4,28.470,4488.0,14,33,93,Lucien Petit-Breton,United States,Cycles Peugeot,Paris - Paris,"48.8566, 2.3522 - 48.8566, 2.3522",7/8/1907 - 8/4/1907
...,...,...,...,...,...,...,...,...,...,...,...
98,39.880,3496.9,20,153,198,Bradley Wiggins,United States,Team Sky,Liège - Paris,"50.6326, 5.5797 - 48.8566, 2.3522",6/30/2012 - 7/22/2012
99,40.540,3403.5,21,169,198,Chris Froome,United States,Team Sky,Porto Vecchio - Paris,"41.5914, 9.2783 - 48.8566, 2.3522",6/29/2013 - 7/21/2013
100,40.690,3659.0,21,164,198,Vincenzo Nibali,United States,Astana,Leeds - Paris,"53.8578, -1.5023 - 48.8566, 2.3522",7/5/2014 - 7/27/2014
101,39.640,3360.3,21,160,198,Chris Froome,United States,Team Sky,Utrecht - Paris,"52.0907, 5.1214 - 48.8566, 2.3522",7/4/2015 - 7/26/2015
102,39.616,3534.0,21,174,198,Chris Froome,United States,Team Sky,Mont St. Michel - Paris,"48.6361, -1.5115 - 48.8566, 2.3522",7/2/2016 - 7/21/2016